alter table profiles enable row level security;
alter table clients enable row level security;
alter table client_accesses enable row level security;
alter table captacoes enable row level security;
alter table cronograma enable row level security;
alter table tasks enable row level security;
alter table meetings enable row level security;
alter table feedbacks enable row level security;
alter table time_clock enable row level security;
alter table vacations enable row level security;
alter table transactions enable row level security;
alter table leads enable row level security;
alter table budgets enable row level security;
alter table automations enable row level security;
alter table files enable row level security;
alter table notifications enable row level security;
alter table commemorative_dates enable row level security;

create policy "auth all" on profiles for all to authenticated using (true) with check (true);
create policy "auth all" on clients for all to authenticated using (true) with check (true);
create policy "auth all" on client_accesses for all to authenticated using (true) with check (true);
create policy "auth all" on captacoes for all to authenticated using (true) with check (true);
create policy "auth all" on cronograma for all to authenticated using (true) with check (true);
create policy "auth all" on tasks for all to authenticated using (true) with check (true);
create policy "auth all" on meetings for all to authenticated using (true) with check (true);
create policy "auth all" on feedbacks for all to authenticated using (true) with check (true);
create policy "auth all" on time_clock for all to authenticated using (true) with check (true);
create policy "auth all" on vacations for all to authenticated using (true) with check (true);
create policy "auth all" on transactions for all to authenticated using (true) with check (true);
create policy "auth all" on leads for all to authenticated using (true) with check (true);
create policy "auth all" on budgets for all to authenticated using (true) with check (true);
create policy "auth all" on automations for all to authenticated using (true) with check (true);
create policy "auth all" on files for all to authenticated using (true) with check (true);
create policy "auth all" on notifications for all to authenticated using (true) with check (true);
create policy "auth all" on commemorative_dates for all to authenticated using (true) with check (true);
