insert into clients (name, segment, color, initials, mrr, status, plan_name, plan_value, services) values
  ('Alegria Kids', 'Educacao infantil', '#14b8a6', 'AK', 2600, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Aquassafe', 'Tecnologia hidrica', '#0ea5e9', 'AQ', 3800, 'active', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Banca de Sindicos', 'Condominios', '#84cc16', 'BS', 1800, 'active', 'Essencial', 1800, array['gestao_social','design']),
  ('Concept', 'Construcao', '#ef4444', 'CO', 6700, 'onboarding', 'Enterprise', 8900, array['gestao_social','design','trafego','videos','captacao','branding','campanhas','consultoria']),
  ('Dener', 'Industria', '#8b5cf6', 'DE', 3300, 'onboarding', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Eucassel', 'Industria', '#ea580c', 'EU', 4900, 'active', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Franci', 'Beleza', '#eab308', 'FR', 2200, 'paused', 'Essencial', 1800, array['gestao_social','design']),
  ('iGet', 'Tecnologia', '#06b6d4', 'IG', 5800, 'active', 'Enterprise', 8900, array['gestao_social','design','trafego','videos','captacao','branding','campanhas','consultoria']),
  ('ITD', 'Tecnologia', '#7c3aed', 'IT', 4200, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Marmitina', 'Alimentacao', '#f43f5e', 'MA', 2400, 'active', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Natacenter', 'Esporte aquatico', '#8b5cf6', 'NA', 2800, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Precisa Servicos', 'Servicos B2B', '#a855f7', 'PS', 3500, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Pro4saude', 'Saude ocupacional', '#0891b2', 'P4', 4400, 'active', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Qualific', 'Auditoria', '#84cc16', 'QU', 4100, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Rentalsul', 'Locacao', '#22c55e', 'RE', 5200, 'active', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Santuse', 'Saude', '#06b6d4', 'SA', 2900, 'active', 'Essencial', 1800, array['gestao_social','design']),
  ('Socias', 'Cosmeticos', '#f43f5e', 'SO', 3100, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Steel Desk', 'Mobiliario corporativo', '#ec4899', 'SD', 5500, 'late', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Termodron', 'Engenharia', '#f59e0b', 'TE', 4800, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']),
  ('Top Sports', 'Esporte', '#06b6d4', 'TS', 3700, 'active', 'Premium', 5500, array['gestao_social','design','trafego','videos','captacao']),
  ('Weco', 'Industria', '#3b82f6', 'WE', 3200, 'active', 'Crescimento', 3200, array['gestao_social','design','trafego']);
